In [0]:

df_emp_csv=spark.read.option("nullValue","null").csv("/FileStore/sourcetable/emp.csv",header=True,inferSchema=True)
display(df_emp_csv)

EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,UPDATED_DATE
7369,SMITH,CLERK,7902,17-12-1980,800,null,20,2022-01-01T00:00:00.000+0000
7499,ALLEN,SALESMAN,7698,20-02-1981,1600,300,30,2022-01-01T00:00:00.000+0000
7521,WARD,SALESMAN,7698,22-02-1981,1250,500,30,2022-01-01T00:00:00.000+0000
7566,JONES,MANAGER,7839,04-02-1981,2975,null,20,2022-01-05T00:00:00.000+0000
7654,MARTIN,SALESMAN,7698,21-09-1981,1250,1400,30,2022-01-03T00:00:00.000+0000
7698,SGR,MANAGER,7839,05-01-1981,2850,null,30,2022-01-04T00:00:00.000+0000
7782,RAVI,MANAGER,7839,06-09-1981,2450,null,10,2022-01-02T00:00:00.000+0000
7788,SCOTT,ANALYST,7566,19-04-1987,3000,null,20,2022-01-02T00:00:00.000+0000
7839,KING,PRESIDENT,null,01-11-1981,5000,null,10,2022-01-02T00:00:00.000+0000
7844,TURNER,SALESMAN,7698,09-08-1981,1500,0,30,2022-01-02T00:00:00.000+0000
7876,ADAMS,CLERK,7788,23-05-1987,1100,null,20,2022-01-03T00:00:00.000+0000
7900,JAMES,CLERK,7698,12-03-1981,950,null,30,2022-01-03T00:00:00.000+0000
7902,FORD,ANALYST,7566,12-03-1981,3000,null,20,2022-01-03T00:00:00.000+0000
7934,MILLER,CLERK,7782,01-03-1982,1300,null,10,2022-01-03T00:00:00.000+0000
1234,SEKHAR,doctor,7777,null,667,78,80,2022-01-03T00:00:00.000+0000
7369,SMITH,CLERK,7902,17-12-1980,800,null,20,2022-01-04T00:00:00.000+0000
7499,ALLEN,SALESMAN,7698,20-02-1981,1600,300,30,2022-01-04T00:00:00.000+0000
7521,WARD,SALESMAN,7698,22-02-1981,1250,500,30,2022-01-04T00:00:00.000+0000
7566,JONES,MANAGER,7839,04-02-1981,2975,null,20,2022-01-04T00:00:00.000+0000
7654,MARTIN,SALESMAN,7698,21-09-1981,1250,1400,30,2022-01-05T00:00:00.000+0000
7698,SGR,MANAGER,7839,05-01-1981,2850,null,30,2022-01-05T00:00:00.000+0000
7782,RAVI,MANAGER,7839,06-09-1981,2450,null,10,2022-01-05T00:00:00.000+0000
7788,SCOTT,ANALYST,7566,19-04-1987,3000,null,20,2022-01-06T00:00:00.000+0000
7839,KING,PRESIDENT,null,01-11-1981,5000,null,10,2022-01-06T00:00:00.000+0000
7844,TURNER,SALESMAN,7698,09-08-1981,1500,0,30,2022-01-06T00:00:00.000+0000
7876,ADAMS,CLERK,7788,23-05-1987,1100,null,20,2022-01-06T00:00:00.000+0000
7900,JAMES,CLERK,7698,12-03-1981,950,null,30,2022-01-07T00:00:00.000+0000
7902,FORD,ANALYST,7566,12-03-1981,3000,null,20,2022-01-07T00:00:00.000+0000
7934,MILLER,CLERK,7782,01-03-1982,1300,null,10,2022-01-07T00:00:00.000+0000
1234,RAM,CLERK,7457,null,494,588,80,2022-01-07T00:00:00.000+0000
null,null,null,null,null,null,null,null,null
null,null,null,null,null,null,null,null,null
null,null,null,null,null,null,null,null,null

In [0]:
display(df_emp_csv.filter("EMPNO is null").count())

3

In [0]:
df_emp_csv.columns

Out[4]: ['EMPNO',
 'ENAME',
 'JOB',
 'MGR',
 'HIREDATE',
 'SAL',
 'COMM',
 'DEPTNO',
 'UPDATED_DATE']

In [0]:

from pyspark.sql.functions import count,col,when
# Take null values count at each column
null_cols = df_emp_csv.select([count(when(col(c).isNull(), c)).alias(c) for c in df_emp_csv.columns])
display(null_cols)
# Filter only columns are having null record count..
df_out = null_cols.select([key for (key,value) in null_cols.collect()[0].asDict().items() if value> 0])
df_out.show()

EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,UPDATED_DATE
3,3,3,5,5,3,23,3,3

+-----+-----+---+---+--------+---+----+------+------------+
|EMPNO|ENAME|JOB|MGR|HIREDATE|SAL|COMM|DEPTNO|UPDATED_DATE|
+-----+-----+---+---+--------+---+----+------+------------+
|    3|    3|  3|  5|       5|  3|  23|     3|           3|
+-----+-----+---+---+--------+---+----+------+------------+

In [0]:
from pyspark.sql.functions import count,col
display(df_emp_csv.select([count(when(col(i).isNull(),i)).alias(i) for i in df_emp_csv.columns]))

EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,UPDATED_DATE
3,3,3,5,5,3,23,3,3